# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Movie.create!(title: 'The Conjuring', genre: 'horror', release_date: Time.now, approved: true, featured: true, duration: 120, description: 'The Conjuring is a 2013 American supernatural horror film directed by James Wan and written by Chad Hayes and Carey Hayes. The film is the first installment in The Conjuring film series.', trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/k10ETZ41q5o" frameborder="0" allowfullscreen></iframe>')
Movie.create!(title: 'Captain America: Civil War', genre: 'fantasy', release_date: Time.now, approved: true, featured: true, duration: 147, description: 'Captain America: Civil War is a 2016 American superhero film featuring the Marvel Comics character Captain America, produced by Marvel Studios and distributed by Walt Disney Studios Motion Pictures. It is the sequel to 2011 movie Captain America: The First Avenger and 2014 movie Captain America: The Winter Soldier, and the thirteenth film of the Marvel Cinematic Universe (MCU).', trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/dKrVegVI0Us" frameborder="0" allowfullscreen></iframe>')
Movie.create!(title: 'Zootopia', genre: 'animation', release_date: Time.now, approved: true, featured: true, duration: 108, description: 'Zootopia (released as Zootropolis in European countries) is a 2016 American 3D computer-animated buddy cop comedy mystery adventure film produced by Walt Disney Animation Studios and released by Walt Disney Pictures. It is the 55th animated feature in the Walt Disney Animated Classics series. ', trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Y0c3nKWhlIA" frameborder="0" allowfullscreen></iframe>')
Movie.create!(title: 'X-Men: Apocalypse', genre: 'fantasy', release_date: Time.now, approved: true, featured: false, duration: 144, description: 'X-Men: Apocalypse is a 2016 American superhero film based on the fictional X-Men characters that appear in Marvel Comics. It is the ninth installment in the X-Men film series and a sequel to X-Men: Days of Future Past.', trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/COvnHv42T-A" frameborder="0" allowfullscreen></iframe>')
Movie.create!(title: 'Lights Out', genre: 'horror', release_date: Time.now, approved: true, featured: false, duration: 315, description: 'Lights Out is a 2016 American supernatural horror film, directed by David F. Sandberg (in his major directorial debut), written by Eric Heisserer, and starring Teresa Palmer, Gabriel Bateman, Billy Burke and Maria Bello.', trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Ct8kBEWmG_s" frameborder="0" allowfullscreen></iframe>')
Movie.create!(title: 'Poltergeist', genre: 'horror', release_date: Time.now, approved: true, featured: true, duration: 102, description: 'Poltergeist is a 2015 American 3D supernatural horror film directed by Gil Kenan, written by David Lindsay-Abaire, and produced by Roy Lee & Sam Raimi.', trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/HD2sz9RVzfM" frameborder="0" allowfullscreen></iframe>')
Movie.create!(title: 'The Nice Guys', genre: 'crime', release_date: Time.now, approved: true, featured: false, duration: 116, description: 'The Nice Guys is a 2016 American comedy thriller film directed by Shane Black and written by Anthony Bagarozzi and Black.', trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/LUbjy4cMlUM" frameborder="0" allowfullscreen></iframe>')
Movie.create!(title: 'Deadpool', genre: 'fantasy', release_date: Time.now, approved: true, featured: false, duration: 210, description: 'Deadpool is a 2016 American superhero film directed by Tim Miller, produced by Lauren Shuler Donner and Simon Kinberg, and written by Rhett Reese and Paul Wernick, based on the Marvel Comics character Deadpool.', trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Xithigfg7dA" frameborder="0" allowfullscreen></iframe>')
Movie.create!(title: 'The Intervention', genre: 'comedy', release_date: Time.now, approved: true, featured: false, duration: 100, description: 'The Intervention is a 2016 American comedy-drama film written and directed by Clea DuVall in her directorial debut.', trailer: '<iframe width="560" height="315" src="https://www.youtube.com/embed/Ba2x_4iktKI" frameborder="0" allowfullscreen></iframe>')
